export const state = () => {
  models: [{
    make: 'iPhone',
    model: [
      'iPhone 5',
      'iPhone 5s',
      'iPhone SE',
      'iPhone 6',
      'iPhone 6s',
      'iPhone 7',
      'iPhone 8',
      'iPhone 6+',
      'iPhone 6s+',
      'iPhone 7+',
      'iPhone 8+ ',
      'iPhone X',
      'iPhone Xs',
      'iPhone XR',
      'iPhone Xs Max',
      'iPhone 11',
      'iPhone 11 Pro',
      'iPhone 11 ProMax'
    ]
  }, {
    make: 'Oppo',
    model: [
      'Oppo A37',
      'Oppo A57',
      'Oppo A39',
      'Oppo A3s',
      'Oppo A12E',
      'Oppo F1S',
      'Oppo A71',
      'Oppo A83',
      'Oppo F3',
      'Oppo F3+',
      'Oppo F5',
      'Oppo F7 Youth',
      'Oppo F7',
      'Oppo A31 2020',
      'Oppo F9',
      'Oppo A5s',
      'Oppo A7',
      'Oppo A12',
      'Oppo F11',
      'Oppo F11 Pro',
      'Oppo A52',
      'Oppo A72',
      'Oppo A92',
      'Oppo A9 2020',
      'Oppo A5 2020',
      'Oppo Reno 2F',
      'Oppo Reno3  2019 5G '
    ]
  }, {
    make: 'Realme',
    model: [
      'Realme 3 ',
      'Realme 3 Pro',
      'Realme C2',
      'Realme XT',
      'Realme 5',
      'Realme 5i',
      'Realme 6i',
      'Realme C3',
      'Realme 5 Pro',
      'Realme 6',
      'Realme 6 Pro',
      'Realme C11',
      'Realme C12',
      'Realme C15',
      'Realme 7i',
      'Realme 7',
      'Realme 7 Pro'
    ]
  }, {
    make: 'Vivo',
    model: [
      'V7',
      'V7+',
      'V9',
      'Y85 ',
      'Y53 ',
      'Y55',
      'Y55s',
      'V5',
      'V5 Lite',
      'Y11',
      'Y12',
      'Y15',
      'Y17 ',
      'Y71',
      'Y91',
      'Y91i',
      'Y95 ',
      'Y91c',
      'Y81',
      'Y81i ',
      'V11',
      'V11i',
      'V15 ',
      'V15 Pro',
      'V17 Pro ',
      'V17',
      'V19 Neo',
      'V19 ',
      'Y19',
      'S1',
      'S1Pro'
    ]
  } ,{
    make: 'Samsung',
    model: [
      'J8',
      'A6+',
      'A5 2018',
      'A7 2017',
      'A7 2018',
      'A8 Plus',
      'Grand Prime',
      'J2 Prime',
      'J4 2018',
      'J5 2016',
      'J5 Prime',
      'J6 2018',
      'J7 Core',
      'J7 2015',
      'J7 2016',
      'J7 Prime',
      'J7 Plus',
      'J7 Pro',
      'Note 5',
      'Note 8',
      'Note 9',
      'Note 10',
      'Note 10+',
      'S7',
      'S7 Edge',
      'S8',
      'S8+',
      'S9',
      'S9+',
      'S10',
      'S10+',
      'S20',
      'S20+',
      'S20 Ultra',
      'A7 2018',
      'J4+',
      'J6+',
      'A8 2018',
      'A50',
      'A50s',
      'A30s',
      'A30',
      'A20',
      'A01',
      'A11',
      'A21',
      'A31',
      'A51',
      'A71',
      'A91',
      'A70',
      'A10',
      'J2 Pro',
      'A10s',
      'A20s'
    ]
  }, {
    make: 'Huawei',
    model: [
      'Nova 2 Lite',
      'Nova 2i',
      'Nova 3i',
      'Nova 7i',
      'P20 Lite',
      'Y6 2018',
      'Y6 Pro 2019',
      'Y9 2019',
      'Y9 Prime',
      'P30 Lite',
      'Nova 5T',
      'Y7 Pro 2019',
      'y7 2019',
      'Y6s',
      'Y6 Prime 2019',
      'Y9s',
      'Y5P',
      'Y6P',
      'Y7P',
      'Nova 7 SE'
    ]
  },{
    make: 'Xiaomi',
    model: [
      'Redmi 5A',
      'Redmi 6A ',
      'Redmi 7',
      'Redmi Note 7 ',
      'Redmi 7A',
      'Redmi Note 8',
      'Redmi 8A',
      'Redmi Note 8P ro',
      'Pocophone F1',
      'Redmi Note 9',
      'Redmi Note 9s',
      'Note 9 Pro',
      'Redmi 9'
    ]
  }]



}
